language: rust

rust:
        - nightly
        - beta
        - stable

install:
        - git clone https://github.com/aquynh/capstone
        - (cd capstone && git checkout 3.0.3 && sudo make install)
